# Generated by Django 2.1.5 on 2019-02-12 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Link', models.CharField(max_length=2000)),
                ('Comment', models.CharField(blank=True, default=None, max_length=300)),
                ('Published_date', models.DateField(default=datetime.date.today)),
                ('Usage', models.BooleanField(default=False)),
                ('Data_field', models.CharField(blank=True, choices=[('A', '발전사 동향'), ('B', '전력산업/시장'), ('C', '신재생에너지/기술'), ('D', '경제/에너지')], default='m', max_length=1)),
            ],
            options={
                'ordering': ['Data_field', 'Published_date'],
            },
        ),
    ]
