# Generated by Django 2.1.5 on 2019-02-17 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MorningBriefing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Published_date',
            field=models.DateField(default=datetime.date(2019, 2, 17)),
        ),
    ]
