# Generated by Django 2.1.5 on 2019-02-17 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MorningBriefing', '0002_auto_20190217_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Published_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 17, 1, 49, 56, 88080)),
        ),
    ]
