# Generated by Django 2.1.5 on 2019-02-17 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MorningBriefing', '0003_auto_20190217_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
