# Generated by Django 2.1.5 on 2019-03-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MorningBriefing', '0009_auto_20190227_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=50)),
                ('title', models.TextField(default=None)),
                ('link', models.TextField(default=None)),
                ('published_date', models.DateField(default=None)),
            ],
        ),
    ]
